//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubRP.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClubRP.Views.Home.HomeRessources", typeof(HomeRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notre équipe dévouée se fera un plaisir de vous aider!.
        /// </summary>
        public static string Caption1 {
            get {
                return ResourceManager.GetString("Caption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histoires, trésors, sortilèges vous attendent!.
        /// </summary>
        public static string Caption2 {
            get {
                return ResourceManager.GetString("Caption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notre système de fiches interactive vous facilitera la gestion de vos personnages.
        /// </summary>
        public static string Caption3 {
            get {
                return ResourceManager.GetString("Caption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipe Dynamique!.
        /// </summary>
        public static string Carousel1 {
            get {
                return ResourceManager.GetString("Carousel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scénarios personnalisés!.
        /// </summary>
        public static string Carousel2 {
            get {
                return ResourceManager.GetString("Carousel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiches interactives!.
        /// </summary>
        public static string Carousel3 {
            get {
                return ResourceManager.GetString("Carousel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue sur le site de l&apos;Icosaèdre!.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
    }
}
