// <auto-generated />
namespace ClubRP.Migrations.ApplicationDBContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class joueurAspinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(joueurAspinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201511181829219_joueurAspinfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
