// <auto-generated />
namespace ClubRP.Migrations.ApplicationDBContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dEtEST : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dEtEST));
        
        string IMigrationMetadata.Id
        {
            get { return "201511271825267_dEtEST"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
