//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubRP.Views.Personnages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersoRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersoRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClubRP.Views.Personnages.PersoRessources", typeof(PersoRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        public static string AC {
            get {
                return ResourceManager.GetString("AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus de CA.
        /// </summary>
        public static string ACBonus {
            get {
                return ResourceManager.GetString("ACBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignement.
        /// </summary>
        public static string Alignement {
            get {
                return ResourceManager.GetString("Alignement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string Appraise {
            get {
                return ResourceManager.GetString("Appraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA de l&apos;armure.
        /// </summary>
        public static string ArmureAC {
            get {
                return ResourceManager.GetString("ArmureAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaB.
        /// </summary>
        public static string BaB {
            get {
                return ResourceManager.GetString("BaB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus d&apos;attaque.
        /// </summary>
        public static string BaBBonus {
            get {
                return ResourceManager.GetString("BaBBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équilibre.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluff.
        /// </summary>
        public static string Bluff {
            get {
                return ResourceManager.GetString("Bluff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA du bouclier.
        /// </summary>
        public static string BouclierAC {
            get {
                return ResourceManager.GetString("BouclierAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisme.
        /// </summary>
        public static string Charisme {
            get {
                return ResourceManager.GetString("Charisme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Classe {
            get {
                return ResourceManager.GetString("Classe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalade.
        /// </summary>
        public static string Climb {
            get {
                return ResourceManager.GetString("Climb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string Constitution {
            get {
                return ResourceManager.GetString("Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artisanat.
        /// </summary>
        public static string Craft1 {
            get {
                return ResourceManager.GetString("Craft1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;art.
        /// </summary>
        public static string Craft1Nom {
            get {
                return ResourceManager.GetString("Craft1Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artisanat.
        /// </summary>
        public static string Craft2 {
            get {
                return ResourceManager.GetString("Craft2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;art.
        /// </summary>
        public static string Craft2Nom {
            get {
                return ResourceManager.GetString("Craft2Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artisanat.
        /// </summary>
        public static string Craft3 {
            get {
                return ResourceManager.GetString("Craft3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;art.
        /// </summary>
        public static string Craft3Nom {
            get {
                return ResourceManager.GetString("Craft3Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critique.
        /// </summary>
        public static string Crit {
            get {
                return ResourceManager.GetString("Crit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critique.
        /// </summary>
        public static string Crit2 {
            get {
                return ResourceManager.GetString("Crit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryptage.
        /// </summary>
        public static string Decipher {
            get {
                return ResourceManager.GetString("Decipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dégats.
        /// </summary>
        public static string Degats {
            get {
                return ResourceManager.GetString("Degats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dégats.
        /// </summary>
        public static string Degats2 {
            get {
                return ResourceManager.GetString("Degats2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitesse de déplacement.
        /// </summary>
        public static string Deplacement {
            get {
                return ResourceManager.GetString("Deplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string DetailsArme {
            get {
                return ResourceManager.GetString("DetailsArme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string DetailsArme2 {
            get {
                return ResourceManager.GetString("DetailsArme2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string DetailsArmure {
            get {
                return ResourceManager.GetString("DetailsArmure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string DetailsBouclier {
            get {
                return ResourceManager.GetString("DetailsBouclier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dextérité.
        /// </summary>
        public static string Dexterite {
            get {
                return ResourceManager.GetString("Dexterite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomatie.
        /// </summary>
        public static string Diplomacy {
            get {
                return ResourceManager.GetString("Diplomacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désamorcage.
        /// </summary>
        public static string DisableDevice {
            get {
                return ResourceManager.GetString("DisableDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déguisement.
        /// </summary>
        public static string Disguise {
            get {
                return ResourceManager.GetString("Disguise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Évasion.
        /// </summary>
        public static string EscapeArtist {
            get {
                return ResourceManager.GetString("EscapeArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expérience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dépourvus.
        /// </summary>
        public static string FlatFooted {
            get {
                return ResourceManager.GetString("FlatFooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        public static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrefacon.
        /// </summary>
        public static string Forgery {
            get {
                return ResourceManager.GetString("Forgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renseignement.
        /// </summary>
        public static string GatherInfo {
            get {
                return ResourceManager.GetString("GatherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pièces d&apos;or.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empathie avec les animaux.
        /// </summary>
        public static string HandleAnimal {
            get {
                return ResourceManager.GetString("HandleAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premier soins.
        /// </summary>
        public static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrétion.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toucher.
        /// </summary>
        public static string Hit {
            get {
                return ResourceManager.GetString("Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toucher.
        /// </summary>
        public static string Hit2 {
            get {
                return ResourceManager.GetString("Hit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV.
        /// </summary>
        public static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus d&apos;initative.
        /// </summary>
        public static string InitativeBonus {
            get {
                return ResourceManager.GetString("InitativeBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative.
        /// </summary>
        public static string Initiative {
            get {
                return ResourceManager.GetString("Initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidation.
        /// </summary>
        public static string Intimidate {
            get {
                return ResourceManager.GetString("Intimidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saut.
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connaissance.
        /// </summary>
        public static string Knowledge1 {
            get {
                return ResourceManager.GetString("Knowledge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la connaissance.
        /// </summary>
        public static string Knowledge1Nom {
            get {
                return ResourceManager.GetString("Knowledge1Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connaissance.
        /// </summary>
        public static string Knowledge2 {
            get {
                return ResourceManager.GetString("Knowledge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la connaissance.
        /// </summary>
        public static string Knowledge2Nom {
            get {
                return ResourceManager.GetString("Knowledge2Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connaissance.
        /// </summary>
        public static string Knowledge3 {
            get {
                return ResourceManager.GetString("Knowledge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la connaissance.
        /// </summary>
        public static string Knowledge3Nom {
            get {
                return ResourceManager.GetString("Knowledge3Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connaissance.
        /// </summary>
        public static string Knowledge4 {
            get {
                return ResourceManager.GetString("Knowledge4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la connaissance.
        /// </summary>
        public static string Knowledge4Nom {
            get {
                return ResourceManager.GetString("Knowledge4Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connaissance.
        /// </summary>
        public static string Knowledge5 {
            get {
                return ResourceManager.GetString("Knowledge5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la connaissance.
        /// </summary>
        public static string Knowledge5Nom {
            get {
                return ResourceManager.GetString("Knowledge5Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception auditive.
        /// </summary>
        public static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lutte.
        /// </summary>
        public static string Lutte {
            get {
                return ResourceManager.GetString("Lutte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus de lutte.
        /// </summary>
        public static string LutteBonus {
            get {
                return ResourceManager.GetString("LutteBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malus aux jets.
        /// </summary>
        public static string Malus {
            get {
                return ResourceManager.GetString("Malus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malu aux jets.
        /// </summary>
        public static string MalusBouclier {
            get {
                return ResourceManager.GetString("MalusBouclier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monter de niveau.
        /// </summary>
        public static string MonterNiveau {
            get {
                return ResourceManager.GetString("MonterNiveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacement silencieux.
        /// </summary>
        public static string MoveSilently {
            get {
                return ResourceManager.GetString("MoveSilently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munition.
        /// </summary>
        public static string Munition {
            get {
                return ResourceManager.GetString("Munition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munition.
        /// </summary>
        public static string Munition2 {
            get {
                return ResourceManager.GetString("Munition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armure naturelle.
        /// </summary>
        public static string NaturalAC {
            get {
                return ResourceManager.GetString("NaturalAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau.
        /// </summary>
        public static string Niveau {
            get {
                return ResourceManager.GetString("Niveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arme principale.
        /// </summary>
        public static string NomArme {
            get {
                return ResourceManager.GetString("NomArme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arme secondaire.
        /// </summary>
        public static string NomArme2 {
            get {
                return ResourceManager.GetString("NomArme2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armure.
        /// </summary>
        public static string NomArmure {
            get {
                return ResourceManager.GetString("NomArmure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouclier.
        /// </summary>
        public static string NomBouclier {
            get {
                return ResourceManager.GetString("NomBouclier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du personnage.
        /// </summary>
        public static string NomPerso {
            get {
                return ResourceManager.GetString("NomPerso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crochetage.
        /// </summary>
        public static string OpenLock {
            get {
                return ResourceManager.GetString("OpenLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Représentation.
        /// </summary>
        public static string Perform1 {
            get {
                return ResourceManager.GetString("Perform1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la représentation.
        /// </summary>
        public static string Perform1Nom {
            get {
                return ResourceManager.GetString("Perform1Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Représentation.
        /// </summary>
        public static string Perform2 {
            get {
                return ResourceManager.GetString("Perform2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la représentation.
        /// </summary>
        public static string Perform2Nom {
            get {
                return ResourceManager.GetString("Perform2Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string Profession1 {
            get {
                return ResourceManager.GetString("Profession1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la profession.
        /// </summary>
        public static string Profession1Nom {
            get {
                return ResourceManager.GetString("Profession1Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string Profession2 {
            get {
                return ResourceManager.GetString("Profession2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la profession.
        /// </summary>
        public static string Profession2Nom {
            get {
                return ResourceManager.GetString("Profession2Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réduction de dégats.
        /// </summary>
        public static string ReductionDegat {
            get {
                return ResourceManager.GetString("ReductionDegat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réflexes.
        /// </summary>
        public static string Reflexe {
            get {
                return ResourceManager.GetString("Reflexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus de réflexes.
        /// </summary>
        public static string ReflexeBonus {
            get {
                return ResourceManager.GetString("ReflexeBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résistance aux sorts.
        /// </summary>
        public static string ResistanceSort {
            get {
                return ResourceManager.GetString("ResistanceSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équitation.
        /// </summary>
        public static string Ride {
            get {
                return ResourceManager.GetString("Ride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagesse.
        /// </summary>
        public static string Sagesse {
            get {
                return ResourceManager.GetString("Sagesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fouille.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychologie.
        /// </summary>
        public static string SenseMotive {
            get {
                return ResourceManager.GetString("SenseMotive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vol a la tire.
        /// </summary>
        public static string SleightOfHand {
            get {
                return ResourceManager.GetString("SleightOfHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art de la magie.
        /// </summary>
        public static string Spellcraft {
            get {
                return ResourceManager.GetString("Spellcraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détection.
        /// </summary>
        public static string Spot {
            get {
                return ResourceManager.GetString("Spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survie.
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natation.
        /// </summary>
        public static string Swim {
            get {
                return ResourceManager.GetString("Swim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC au contact.
        /// </summary>
        public static string TouchAC {
            get {
                return ResourceManager.GetString("TouchAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobaties.
        /// </summary>
        public static string Tumble {
            get {
                return ResourceManager.GetString("Tumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;armure.
        /// </summary>
        public static string TypeArmure {
            get {
                return ResourceManager.GetString("TypeArmure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisation d&apos;objets magiques.
        /// </summary>
        public static string UMD {
            get {
                return ResourceManager.GetString("UMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maîtrise des cordes.
        /// </summary>
        public static string UseRope {
            get {
                return ResourceManager.GetString("UseRope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigueur.
        /// </summary>
        public static string Vigueur {
            get {
                return ResourceManager.GetString("Vigueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus de vigueur.
        /// </summary>
        public static string VigueurBonus {
            get {
                return ResourceManager.GetString("VigueurBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir la fiche .
        /// </summary>
        public static string VoirFiche {
            get {
                return ResourceManager.GetString("VoirFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volonté.
        /// </summary>
        public static string Volonte {
            get {
                return ResourceManager.GetString("Volonte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus de volonté.
        /// </summary>
        public static string VolonteBonus {
            get {
                return ResourceManager.GetString("VolonteBonus", resourceCulture);
            }
        }
    }
}
