//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubRP.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClubRP.Views.Shared.ContentRessources", typeof(ContentRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À l&apos;origine nous voulions simplement nous promener d&apos;un endroit à un autre, écoles, magasins, etc. dans le but de promouvoir les jeux de rôles, inciter les jeunes à embarquer dans des aventures. Par contre, on est rapidement arrivé à une conclusion, il y a déjà beaucoup de joueurs, mais ils sont tous séparés, isolés dans de petites cellules sans                même avoir conscience de la quantité de joueurs qui les entourent. Cela pose problème pour plusieurs, qui ont soit perdu leurs groupes ou cherchent t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutFounderMessage {
            get {
                return ResourceManager.GetString("AboutFounderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nommé par la forme de l&apos;iconique dé à 20 faces des jeux de rôles, l&apos;Icosaèdre a été fondé en 2007 par les cofondateurs Nathan Bélanger, Patrick Delorme et Cédric Castelneau, trois amis de longue date passionnés de jeux de rôles cherchant à régler un problème désolant dans la communauté des rôlistes, le manque d&apos;un réseau permettant à des joueurs de se trouver des compagnons de jeu. Ils décidèrent donc de créer un endroit agréable pour les rôlistes de tous niveaux, d&apos;initiation aux débutants, mais surtout un [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutFounderTitle {
            get {
                return ResourceManager.GetString("AboutFounderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voici un message des fondateurs: .
        /// </summary>
        public static string AboutIntro {
            get {
                return ResourceManager.GetString("AboutIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4428 rue Wellington.
        /// </summary>
        public static string ContactAddress1 {
            get {
                return ResourceManager.GetString("ContactAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montréal, QC Y7D 9M8.
        /// </summary>
        public static string ContactAddress2 {
            get {
                return ResourceManager.GetString("ContactAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance: .
        /// </summary>
        public static string ContactAssistance {
            get {
                return ResourceManager.GetString("ContactAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez nous contacter par téléphone du lundi au vendredi de 9:00 à 21:00 et la fin de  semaine  de 12:00 a 23:00 ou par courriel en tout temps (délai de 24 heures maximum possible), ainsi que par la poste à l&apos;adresse ci-dessus..
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string ContactTelephone {
            get {
                return ResourceManager.GetString("ContactTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour les joueurs à plus grand budget, voici un montage vidéo des jeux de rôle du future avec projecteur!
        ///    &lt;br /&gt;&lt;iframe width=&quot;560&quot; height=&quot;315&quot; src=&quot;https://www.youtube.com/embed/5bmOu3XcJuU&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;&lt;br /&gt;   Et voici ou l&apos;on peut les retrouver: &lt;a hhref=&quot;http://www.amazon.ca/FastFox-Projector-Multimedia-Protable-Proyector/dp/B00ZI978XK/ref=sr_1_1?ie=UTF8&amp;qid=1442168797&amp;sr=8-1&amp;keywords=projector&quot;&gt;Projecteur simple&lt;/a&gt;
        ///    &lt;a hhref=&quot;http://www.amazon.ca/BenQ-MS524-Lumen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EquipProjector {
            get {
                return ResourceManager.GetString("EquipProjector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaque joueur doit aussi avoir &lt;a target=&quot;_blank&quot; href=&quot;http://www.imaginaire.com/indexv2.jsp?url=/recherchev2/avance2.jsp&amp;cat1=GA&amp;cat2=DE&quot;&gt;ses dés&lt;/a&gt; de sa couleur préférée! Sans eux, il n&apos;y a pas beaucoup de jeu de rôle possible....
        /// </summary>
        public static string EquipRequirement {
            get {
                return ResourceManager.GetString("EquipRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez trouver ici un exemple à quoi ressemble notre espace client. Nous vous proposons plusieurs outils
        ///    qui vous aideront à apprécier encore plus votre partie de jeu.
        ///    Par exemple, &lt;a target=&quot;_blank&quot; href=&quot;http://www.amazon.ca/Chessex-Role-Playing-Play-Mat/dp/B0015IQO2O/ref=pd_sim_t_2?tag=8013013-20&quot;&gt;ce tapis quadrillé&lt;/a&gt; pour faciliter le calcul des déplacements de vos figurines. Il est aussi utilisé pour dessiner ses plans de dungeon
        ///    avec des crayons non permanents et tout simplement  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EquipText {
            get {
                return ResourceManager.GetString("EquipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue sur notre forum!.
        /// </summary>
        public static string ForumWelcome {
            get {
                return ResourceManager.GetString("ForumWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une fiche assistée pour la création de leurs personnages.
        /// </summary>
        public static string IndexList1 {
            get {
                return ResourceManager.GetString("IndexList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un espace de notes, pour se souvenir des moments cruciaux de leur partie.
        /// </summary>
        public static string IndexList2 {
            get {
                return ResourceManager.GetString("IndexList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès a notre base de données.
        /// </summary>
        public static string IndexList3 {
            get {
                return ResourceManager.GetString("IndexList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès a un forum.
        /// </summary>
        public static string IndexList4 {
            get {
                return ResourceManager.GetString("IndexList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selon le niveau d&apos;implication, la possibilité d&apos;être invité à des événements exclusifs et des rabais sur certains produits.
        /// </summary>
        public static string IndexList5 {
            get {
                return ResourceManager.GetString("IndexList5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaque membre aura le droit à: .
        /// </summary>
        public static string IndexMembers {
            get {
                return ResourceManager.GetString("IndexMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue sur la nouvelle plateforme interactive de l&apos;Icosaèdre!.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet outil a été conceptualisé dans le but de rendre vos parties plus intéressantes et limiter l&apos;utilisation de papier grâce à nos outils extraordinaires! En créant un compte sur notre application, vous pourrez choisir quel rôle vous voulez avoir durant la partie (joueur ou maître de jeu), augmenter le rythme de jeu avec nos outils d&apos;assistance tout en réduisant la complexité d&apos;une partie. Vous pourrez aussi sauvegarder votre personnage dans notre base de données et pourrez l&apos;exporter dans tous nos (futurs)  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexWebsite {
            get {
                return ResourceManager.GetString("IndexWebsite", resourceCulture);
            }
        }
    }
}
